version: '3.7'
services:
  app:
    build:
      args:
        user: hamza
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: reco
    container_name: reco-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - reco
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: reco-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: $DB_DATABASE
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_USER: $DB_USERNAME
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - reco

  nginx:
    image: nginx:alpine
    container_name: reco-nginx
    restart: unless-stopped
    ports:
      - '8000:80'
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - reco

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.2
    networks:
      - reco
    ports:
      - '8081:80'
    environment:
      PMA_HOST: db
    depends_on:
      - db

networks:
  reco:
    driver: bridge
